version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid:/etc/selenoid"
    command: ["-limit", "4", "-timeout", "60s"]

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid-ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

volumes:
  jenkins_home:
